### ISSUE TITLE
Testing multiple URLs but results are stored in the same folder

### ISSUE THREAD

**Issue by gensychong** [sitespeedio/dashboard.sitespeed.io#27]
Hi, I have just started to learn how to use sitespeed.io for my projects and I am able to setup the grafana in Digital Ocean. While I am testing this script to continuously run the test, I meet some issues.

1. I am using exactly the same settings in this repo and only modify the necessary like graphite host/auth, URLs to test in desktop.txt and etc.
2. I am testing multiple pages in multiple domains. 
Example: 
**abc.com
abc.com/products
abc.com/about-us
def.com
def.com/products
def.com/about-us**
3. I am assuming the results will be stored in separate folder under abc.com/def.com folder.  But it is currently stored as following:
**/sitespeed-result/abc.com/[DATE]/pages/abc.com
/sitespeed-result/abc.com/[DATE]/pages/def.com**

May I know if this can be configured to do as below?
**/sitespeed-result/abc.com/[DATE]/
/sitespeed-result/def.com/[DATE]/**

**Comment by soulgalore** [comment]
Hi @gensychong they are stored in the same folder. If you need to have them on different folders, you need to split the tests and run it two times:
```
abc.com
abc.com/products
abc.com/about-us
```

and then 
```
def.com
def.com/products
def.com/about-us
```

**Comment by gensychong** [comment]
Thanks @soulgalore, I was thinking if it can run at the same time but store in different folders. Thanks for the help!
