### ISSUE TITLE
Disable favicon

### ISSUE THREAD

**Issue by dbrau** [sitespeedio/dashboard.sitespeed.io#28]
Dear sitespeed-team,
we are using sitespeed dashboard to monitoring and analyze some of our websites. 
I added some lines of our website in the file

> ../tests/FOLDERNAME/desktop/urls/startpage.txt

One every run I get an following error in /tmp/<logfilename>.log

> Google Chrome 80.0.3987.132 
> Mozilla Firefox 74.0
> [2020-04-01 13:06:36] INFO: Versions OS: linux 4.15.0-72-generic nodejs: v12.13.0 sitespeed.io: 12.3.1 browsertime: 8.3.1 coach: 5.0.1
> [2020-04-01 13:06:36] INFO: Running tests using Chrome - 1 iteration(s)
> [2020-04-01 13:06:38] INFO: Testing url URL iteration 1
> [2020-04-01 13:07:37] INFO: URL 20 requests, backEndTime: 8.18s, firstPaint: 16.32s, firstVisualChange: 16.33s, DOMContentLoaded: 16.36s, Load: 24.28s, speedIndex: 16414, perceptualSpeedIndex: 16681, contentfulSpeedIndex: 16337, visualComplete85: 16.33s, lastVisualChange: 24.33s, rumSpeedIndex: 16505
> [2020-04-01 13:07:38] INFO: The server responded with a 404 status code for https://URL/favicon.ico
> [2020-04-01 13:07:41] INFO: HTML stored in /sitespeed.io/sitespeed-result/URL/2020-04-01-13-06-36
> ./sitespeed.run found. Make another run ..

I also getting the INFO message when I'm using javascript. 

Now my first question: Is the absence of the favicon also included in the calculation of the time?
Secound question: It is possible to disable downloading the favicon?

Thank you very much

**Comment by soulgalore** [comment]
Hi @dbrau 

>  Is the absence of the favicon also included in the calculation of the time?

The browser automatically do the request for the favicon and that GET request is included the HAR file, that's why you get that 404. Included in the timing: not 100% what you mean but that request is included when you test and it's done by the browser, but my guess is that it will not have so much impact on your timings.

>  It is possible to disable downloading the favicon?

Maybe Firefox have some preferences to remove it and [Chrome some CLI](https://peter.sh/experiments/chromium-command-line-switches/) but I haven't looked.

Best
Peter

**Comment by dbrau** [comment]
Dear Peter,
thank you for the response. 
We are suspect that the timing of your test results are too high and I suspected the favicon "error". That's why i asked. 
Normally we are using nagios and the plugin "check_http". This [plugin](https://www.monitoring-plugins.org/doc/man/check_http.html) checks the connection time to an url (see the link to find out more of the plugin). Now we are trying to find out almost the same time with sitespeed. 
Do you have any experience with the plugin and sitespeed?

I hope you understand what I mean. I come from germany and to write a description of the problem in english is unfortunately not what I doing every day ^^ If anything is unclear please ask.

Thanks you
Danny

**Comment by soulgalore** [comment]
Hi @dbrau ah I see. Your English works good, no problem at all, and ist besser als mein Deutsch :)

I think you are comparing different things? Or how do the check_http plugin works? I think it checks for the main page to be downloaded (the HTML). With sitespeed.io you are measuring the full page will all the JavaScript, CSS, images etc? If you just want to look at server timings (like the time it takes for the server to generate the page in the back) you can look at back end time https://www.sitespeed.io/documentation/sitespeed.io/metrics/#browser-metrics .

Let me know what metrics you want to track or interested in and I can help out explain them.

Best
Peter

**Comment by dbrau** [comment]
Hey Peter, thank you for the response. 

the result of the nagios plugin "check_http" is something like:
`HTTP OK: HTTP/1.1 200 OK - 18544 bytes in 0.035 second response time`

So everything is fine with the website. Response 200 ok and the time is 0,035 second.

I'm aware that sitespeed can do much more than the plugin - that's one reason why we want to use it -  but I think we don't using it "correctly" yet. So far we have only had experience with the "check_http" - plugin. 

What we need:
We want to measure the time that user have when they visit the website. That's the "only" thing we want to do for now. For example: When I open firefox or chrome - doesn't matter which one - enter the url of a website and confirm the browser to loading the site. A "good" website should responds in milliseconds - what the user means at least. Sure, the website are loading so much more in the background but we need the time the user have. When your sites were to slow the user wouldn't use the site. 

Is it even possible to determine the individual value at all? Does it make sense?

Thanks you very much
Danny

**Comment by dbrau** [comment]
fix the problem in issue #29 
Thanks your
